ENV="dev"
WORKSTATION_IP="172.31.94.85/32"

# RDS
RDS_MYSQL_PORT  = 3306
RDS_MYSQL_STORAGE = 10
RDS_ENGINE_VERSION = "5.7"
RDS_INSTANCE_TYPE = "db.t3.micro"

#Mongo
DOCUMENTDB_PORT = 
DOCUMENTDB_INSTANCE_CLASS =
DOCUMENTDB_INSTANCE_COUNT =